name: SimulaHS
version: 0.0.0
synopsis: Haskell/C++ implementation of simula_cpp
author: David Kraeutmann <kane@kane.cx>

default-extensions:
  - GADTs
  - ConstraintKinds
  - KindSignatures
  - StandaloneDeriving
  - FlexibleInstances
  - FlexibleContexts
  - MultiParamTypeClasses
  - FunctionalDependencies
  - ScopedTypeVariables
  - RankNTypes
  - RecursiveDo
  - DefaultSignatures
  - PatternSynonyms
  - LambdaCase
  - ForeignFunctionInterface
  - QuasiQuotes
  - TemplateHaskell
  - OverloadedStrings

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - clock
  - containers
  - file-embed
  - hashable
  - inline-c
  - inline-c-cpp
  - lens
  - linear
  - linear-opengl
  - monad-loops
  - mtl
  - OpenGL
  - OpenGLRaw
  - primitive
  - unordered-containers
  - template-haskell
  - transformers
  - text
  - vector
  - unix
  - StateVar
  - simula-wayland
  - simula-osvr



_executable_options: &executable_options
  dependencies: [base, SimulaHS]
  ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    
library:
  source-dirs: src
  c-sources:
    - simula-wayland/cbits/*.c
    - src/**/*.c
  include-dirs:
    - simula-wayland/cbits

  exposed-modules:
    - Simula.Utils
    - Simula.Compositor.SceneGraph
    - Simula.Compositor.SceneGraph.Wayland
    - Simula.Compositor.OpenGL
    - Simula.Compositor.Types
    - Simula.Compositor.Utils
    - Simula.Compositor.Compositor
    - Simula.Compositor.WindowManager
    - Simula.Compositor.Wayland.Input
    - Simula.Compositor.Wayland.Output
    - Simula.Compositor.Geometry
    - Simula.Compositor.Weston

executables:
  simple-compositor:
    <<: *executable_options
    main: SimpleCompositor.hs
    source-dirs: app
    dependencies: [dbus, SimulaHS]
