name: Simula
version: 0.0.0
synopsis: 3D window mamanger for Linux.
author: Simula Team <george.w.singer@gmail.com>

default-extensions:
  - GADTs
  - ConstraintKinds
  - KindSignatures
  - StandaloneDeriving
  - FlexibleInstances
  - FlexibleContexts
  - MultiParamTypeClasses
  - FunctionalDependencies
  - ScopedTypeVariables
  - RankNTypes
  - RecursiveDo
  - DefaultSignatures
  - PatternSynonyms
  - LambdaCase
  - ForeignFunctionInterface
  - QuasiQuotes
  - TemplateHaskell
  - OverloadedStrings
  - TupleSections

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - clock
  - containers
  - file-embed
  - hashable
  - inline-c
  - inline-c-cpp
  - lens
  - linear
  - linear-opengl
  - monad-loops
  - mtl
  - optparse-applicative
  - OpenGL
  - OpenGLRaw
  - primitive
  - unordered-containers
  - template-haskell
  - transformers
  - text
  - vector
  - unix
  - StateVar
  - simula-wayland
  - simula-openvr
  - vulkan
  - vector-sized
_executable_options: &executable_options
  dependencies: [base, Simula]
  ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    
library:
  source-dirs: src
  c-sources:
    - simula-wayland/cbits/*.c
    - src/**/*.c
  include-dirs:
    - simula-wayland/cbits

  exposed-modules:
    - Simula.Utils
    - Simula.BaseCompositor.SceneGraph
    - Simula.BaseCompositor.SceneGraph.Wayland
    - Simula.BaseCompositor.OpenGL
    - Simula.BaseCompositor.Types
    - Simula.BaseCompositor.Utils
    - Simula.BaseCompositor.Compositor
    - Simula.BaseCompositor.WindowManager
    - Simula.BaseCompositor.Wayland.Input
    - Simula.BaseCompositor.Wayland.Output
    - Simula.BaseCompositor.Geometry
    - Simula.BaseCompositor.Weston
    - Simula.ViveCompositor.ViveCompositor
    - Simula.ViveCompositor.SimulaVRModel

executables:
  simulavr:
    <<: *executable_options
    main: SimulaVR.hs
    source-dirs: app
    dependencies: [dbus, Simula]
