resolver: nightly-2019-01-15

packages:
- .

extra-deps:
- git: https://gitlab.com/lboklin/godot-extra
  commit: 495850e3c1d50b4a869becaaf9f0aed467a85b32 # signals branch
- ./godot-haskell-gdwlroots-3.1.0.0.tar.gz # gdwlroots-3.1 branch
- casing-0.1.4.0@sha256:a1ea21789906302930300b68ffd40373bc731e9254b43d1f35e8ba7368b2acce,1029
- data-flags-0.0.3.4
- git: https://github.com/SimulaVR/hsroots
  commit: 4eb41e73a75cd05c6cf2baf0e7c20deea26f713b
- git: https://github.com/SimulaVR/haskell-wayland
  commit: f51e19511fdb13f747ae57d9aad6752fdaea6bb6
- git: https://github.com/Ongy/haskell-xkbcommon.git
  commit: a1455b51c053289b1b5b27d19d4159180647228d
- git: https://github.com/georgewsinger/libinput
  commit: 68088b5acdda3e3e8121e6dafa34f295bf35c121
- git: https://github.com/SimulaVR/cpphs
  commit: 07946d7d768f385dc86c3f3f6872983c08245e26

require-stack-version: ">=1.7.1 && <1.11"

nix:
  enable: false
  shell-file: shell.nix
