name: "cachix-pusher"

on:
  push:
    branches:
      - master
    tags:
      - *

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: simula
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
