name: nix-checker

on:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - 'main'

permissions: {}

jobs:
  run-nix-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install Nix
        uses: cachix/install-nix-action@v31.1.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run nix flake check
        run: nix flake check --all-systems
  run-nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install Nix
        uses: cachix/install-nix-action@v31.1.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run nix-build with flakes
        run: nix build -L
